BASE_URL = "https://api.mangadex.org"
LANGUAGES = "en"

scanlation_groups = {
    "preferred_groups": [
        "LHTranslation",
        "Galaxy Degen Scans",
        "The Golden Orchid",
        "Baddies' Asylum",
        "Web Novel Translation - Scanlation Division",
        "Soseki Scans",
        "Mangasushi",
        "Silicon Signature Swisse ",
        "Blooming Tea Scans",
        "3.14rate",
        "Weeblet80",
        "MelonMelonHydra",
        "Kazokuden",
        "Kredim",
        "alt.ver.",
        "Uxtef's Translations",
        "Impatient Scans",
        "hidamari",
        "Asura Scans",
        "Reaper Scans",
        "spell caster",
        "Terribly Incompetent Scans",
        "Rainy Days",
        "Spaghetti Translation",
        "Infrequent scans",
        "LazyReader",
        "PaceBellum Scan",
        "/ak/ scanlations",
        "YumScans",
        "potatofoodscans",
        "People of Refined Taste",
        "Cave Drawings",
        "The Abandoned",
        "Flame Scans",
        "Flame Comics",
        "Carefree scanlations",
        "Spaghetti Monsters",
        "Shinsei Scans",
        "Flaemes TL",
        "Wakga",
        "SuNday",
        "XuN",
        "Aphrodite Scans",
        "Daddy, Scan me Harder!",
        "Akuyaku Scans",
        "Jai Random Scans",
        "Kuma Translation",
        "no sleep group",
        "Hunlight Scans",
        "Hatch Potch Cafe",
        "Sugoi-Sugoi",
        "Hazue Ishin",
        "INP-Mangaz",
        "Whimsubs",
        "Inferno Scan",
        "SomethingAboutScans",
        "Not a Scans Scans Group",
        "Neon_Scans",
        "DFlow Scans",
        "`Nekyou",
        "Schale scans",
        "Failure at Grammar",
        "kumakumakugroup",
        "KS Group",
        "MSPaintCans"
    ],
    "preferred_users": [
        "xxxbatskaterxxx",
        "Amarrez"
    ],
    "blacklisted_groups": []
}