import os, stat

BASE_URL = "https://api.mangadex.org"
LANGUAGES = "en"

scanlation_groups = {
    "preferred_groups": [
        "LHTranslation",
        "Galaxy Degen Scans",
        "The Golden Orchid",
        "Baddies' Asylum",
        "Web Novel Translation - Scanlation Division",
        "Soseki Scans",
        "Mangasushi",
        "Silicon Signature Swisse ",
        "Blooming Tea Scans",
        "The Abandoned",
        "3.14rate",
        "Weeblet80",
        "MelonMelonHydra",
        "Kazokuden",
        "Kredim",
        "alt.ver.",
        "Uxtef's Translations",
        "Impatient Scans",
        "hidamari",
        "Asura Scans",
        "Reaper Scans",
        "spell caster",
        "Terribly Incompetent Scans",
        "Rainy Days",
        "Spaghetti Translation",
        "Infrequent scans",
        "LazyReader",
        "PaceBellum Scan",
        "/ak/ scanlations",
        "YumScans",
        "potatofoodscans",
        "People of Refined Taste",
        "Party Scans",
        "Cave Drawings",
        "Flame Scans",
        "Flame Comics",
        "Carefree scanlations",
        "Spaghetti Monsters",
        "Shinsei Scans",
        "Flaemes TL",
        "Wakga",
        "SuNday",
        "XuN",
        "HAMASCANS",
        "Chibi Multiverse",
        "Aphrodite Scans",
        "Daddy, Scan me Harder!",
        "The Fluffy Hangout Group",
        "FairyScans",
        "FML Translations",
        "Endless Journey",
        "/a/nonymous",
        "Akuyaku Scans",
        "Vanguard",
        "Manga Galaxy",
        "koppisekai"
        "Skythewood", 
        "Jai Random Scans",
        "Kuma Translation",
        "no sleep group",
        "Hunlight Scans",
        "Hatch Potch Cafe",
        "West",
        "No Works",
        "Sugoi-Sugoi",
        "MANA SCANS",
        "Levscans",
        "My Darling",
        "Petrichor",
        "Einherjar Scan",
        "Revelion Scan",
        "M107 Sniper Rifle",
        "Infinity Scan",
        "Hazue Ishin",
        "the swaggoneers",
        "INP-Mangaz",
        "Whimsubs",
        "Inferno Scan",
        "Hero?",
        "ColorNoobs",
        "Mistakes Were Made",
        "Bewitched",
        "waddles_scans",
        "abandoned kitten scans",
        "SomethingAboutScans",
        "Not a Scans Scans Group",
        "Neon_Scans",
        "DFlow Scans",
        "`Nekyou",
        "Schale scans",
        "Failure at Grammar",
        "kumakumakugroup",
        "KS Group",
        "MSPaintCans"
    ],
    "preferred_users": [
        "xxxbatskaterxxx",
        "Amarrez",
        "Quanshiro",
        "Mino5531",
        "tonsoftons",
        "Riko"
    ],
    "blacklisted_groups": []
}

def remove_readonly(func, path, excinfo):
    """Clear the readonly bit and re-attempt the removal"""
    os.chmod(path, stat.S_IWRITE)
    func(path)